### ISSUE TITLE
make it easier to cite posts

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#49]

**Comment by JosephMcArthur** [comment]
We have some examples for how to cite here: https://osf.io/preprints/lissa/a7nk8/

> APA
> Aspesi, C., Allen, N. S., Crow, R., Daugherty, S., Joseph, H., McArthur, J. T. W., & Shockey, N. (2019, November 19). SPARC Roadmap for Action: Academic Community Control of Data Infrastructure. https://doi.org/10.31229/osf.io/a7nk8

> MLA
> Aspesi, Claudio, et al. “SPARC Roadmap for Action: Academic Community Control of Data Infrastructure.” LIS Scholarship Archive, 19 Nov. 2019. Web.

> Chicago
> Aspesi, Claudio, Nicole S. Allen, Raym Crow, Shawn Daugherty, Heather Joseph, Joseph T. W. McArthur, and Nick Shockey. 2019. “SPARC Roadmap for Action: Academic Community Control of Data Infrastructure.” LIS Scholarship Archive. November 19. doi:10.31229/osf.io/a7nk8.

I think it would be rather nice to allow one of this to be copied. Thinking at the level of post, 'cite it' could appear in the same spot as download. Not sure about what to do on reports. 

Some front matter could set the citation, when we have it.

Also, the DOI will also feel 'academic' to folks, so showing that might just be helpful.

**Comment by JosephMcArthur** [comment]
For posts without reports, we may want to promote citation too. I don't 100% know what's best to do there, perhaps folks should just write it in when posting.

**Comment by ssssoz** [comment]
I can take care of this if you want. I already have a bit of code (in a different templating language) for APA / MLA / Chicago-style citations.

**Comment by JosephMcArthur** [comment]
Ace! Please do. The citation for the landscape analysis is here: https://osf.io/preprints/lissa/58yhb.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by ssssoz** [comment]
For now, all the posts are authored by 

> Aspesi, Claudio, Nicole S. Allen, Raym Crow, Shawn Daugherty, Heather Joseph, Joseph T. W. McArthur, and Nick Shockey 

? 

Or should we add frontmatter for the author(s) of every post?

**Comment by ssssoz** [comment]
I guess that would tie this issue to #73

**Comment by JosephMcArthur** [comment]
Nope, they can differ per report (that's only correct for the first). Presuming this just sets the authorship of the citation, then yes I think just using some frontmatter is great.

**Comment by ssssoz** [comment]
> Nope, they can differ per report (that's only correct for the first). Presuming this just sets the authorship of the citation, then yes I think just using some frontmatter is great.

Clarifying again, we want post- ("article-") level citations but we’re not sure about what to do at the report-level? I’m confused because the sample citation you mention up there has a DOI assigned to the full report, not the single posts (which I think you broke down into shorter posts on the website). 

I have committed the template to generate APA, MLA, & Chicago-style citations, which can be used / included in both `thread.html` (for reports only) and `post.html`. Just need to better understand what goes in the authors and DOI fields.

**Comment by ssssoz** [comment]
Oh and another thing -- the original citations also include the archive (which we do not include in our frontmatter, but won’t be a problem if it’s always going to be on LIS Scholarship Archive), and a subtitle. Do you still want the subtitles?

**Comment by ssssoz** [comment]
# Report-level citation

![daddd58664bc03d4d6290cdbb8b91c0b](https://user-images.githubusercontent.com/6668406/85432493-f3d9db80-b57a-11ea-9569-5cc2e8f23ce1.gif)

---

# Post-level citation 

![3ade4015d34b6f01125bf7a94df4e96a](https://user-images.githubusercontent.com/6668406/85457729-483f8400-b598-11ea-9ba9-cd9112ec2492.gif)

--- 

In order to assign specific authors on a post OR a thread, you just need to list out their "short names" in the front matter for either type of file, like this: 

```
---
layout: thread
title: SPARC Landscape Analysis
authors:
  - claudio
  - nicole
  - raym
  - shawn
  - heather
  - joe
  - nick
[...]
---
```

You can create a new author in the [`_data/authors.yml`](https://github.com/sparcopen/infrastructure/blob/dev/_data/authors.yml) file.  For now, I have everyone + Shawn Daugherty, and "SPARC" as a single entity, if ever you need to use that as an author.

**Comment by ssssoz** [comment]
This is resolved in 9c469d6eb7e563a7e13a5370b4d78ee55f5b6ebe

**Comment by ssssoz** [comment]
- Add post-level URL
- Add report name to which a post belongs

**Comment by ssssoz** [comment]
> * Add post-level URL
> * Add report name to which a post belongs

![f88ac5701d7f3672332919987fa093ff](https://user-images.githubusercontent.com/6668406/85605619-3cac9580-b64a-11ea-82ab-86102b4f1cec.gif)

---

Something else to consider: the right column is starting to become very bloated, especially since it’s "sticky". We should consider moving some of these elements into icons and having them stick on the left side instead (which is already sticky
)

**Comment by JosephMcArthur** [comment]
Small things

- [x] remove tiny 'cite this' after button is clicked
- [x] change button text to `cite`

**Comment by JosephMcArthur** [comment]
I need to do this: https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/#configure-an-apex-domain

**Comment by JosephMcArthur** [comment]
Where did we land with specifying authors for citation and authors for the author box?

**Comment by ssssoz** [comment]
Pushed the two small things to dev! 

> Where did we land with specifying authors for citation and authors for the author box?

I think it should reflect the authors’ box to keep it simple -- so in all cases, for now, the authors in the citation would be Claudio & SPARC (no specific names). It wouldn’t be the same as the citations on LISSA, but it’s up to you. I still don’t fully understand how you want to attribute authorship on a per-post basis.

**Comment by ssssoz** [comment]
The full about page (`/about/`) could explicitly mention that SPARC is Nicole, Heather, Nick, Raym,... You (etc.).

**Comment by JosephMcArthur** [comment]
Gotcha. Let's leave it as is for now. Can you make sure you've taken out any placeholder authorship info?

**Comment by ssssoz** [comment]
Done! And pushed to `dev`

**Comment by ssssoz** [comment]
Citations’ authors are also the same as the author infoboxes’. I also think we should remove the fixed sidebar... the text might be cut off at the bottom for many users.

**Comment by JosephMcArthur** [comment]
on mobile I think we should hide this, and related. It just turns up at the bottom and I think simplifying makes sense. 

![image](https://user-images.githubusercontent.com/4953703/85896100-c6499800-b7ef-11ea-86ee-3686d8c3269a.png)

**Comment by ssssoz** [comment]
Donee & pushed on dev
