### ISSUE TITLE
allow per post authorship

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#73]

**Comment by ssssoz** [comment]
This was already done as part of #49

**Comment by JosephMcArthur** [comment]
Would be good if the author box responded to the new author yaml

**Comment by ssssoz** [comment]
See https://github.com/sparcopen/infrastructure/issues/72#issuecomment-648958495

**Comment by ssssoz** [comment]
Author box + `/about` page include data from `_data/authors.yml` now.

**Comment by JosephMcArthur** [comment]
- [x] the below are just a touch too close together to be easily tab-able on mobile I think

![image](https://user-images.githubusercontent.com/4953703/85898233-d499b300-b7f3-11ea-873d-e21c8c230eb5.png)

- [x] a taste issue with me maybe, but I think a little more padding here would help

![image](https://user-images.githubusercontent.com/4953703/85898331-f98e2600-b7f3-11ea-8691-d458d0d50104.png)


- [x] how big of a pain is it to have sparc* more centred? I realise the image likely is, but it **feels** unaligned

![image](https://user-images.githubusercontent.com/4953703/85898370-0d398c80-b7f4-11ea-8330-552507ee5614.png)

**Comment by ssssoz** [comment]
> the below are just a touch too close together to be easily tab-able on mobile I think

Done, but also changed the typeface to the sans-serif one, just so it's a bit more consistent with the other infobox links & stands out from the rest of the text. 

> how big of a pain is it to have sparc* more centred? I realise the image likely is, but it **feels** unaligned

You’re right, it is not centered -- it’s aligned to the left. Thing is, it’ll always look weird on different devices because of the padding around the infobox box.

This is what it looks like when it’s "properly" aligned:
 
<img width="794" alt="Screenshot 2020-06-30 at 17 50 18" src="https://user-images.githubusercontent.com/6668406/86153862-2bf09980-bafa-11ea-9486-6b61d42f7bbf.png">

<img width="355" alt="Screenshot 2020-06-30 at 17 51 54" src="https://user-images.githubusercontent.com/6668406/86154080-7d008d80-bafa-11ea-9c28-872f21b6414f.png">

You can see that extra padding on the left from its container makes it look off-center: 

<img width="329" alt="Screenshot 2020-06-30 at 17 52 04" src="https://user-images.githubusercontent.com/6668406/86154097-84c03200-bafa-11ea-912b-52a4f0564ce3.png">

...so I made it full-width with a padding on the right side, same size as the container’s. Hope that’s okay; the logo is much bigger now.

<img width="559" alt="Screenshot 2020-06-30 at 17 55 59" src="https://user-images.githubusercontent.com/6668406/86154424-f7311200-bafa-11ea-94d3-0388d466461f.png">

Pushed to dev!
