### ISSUE TITLE
consider a more elegant way to do sub sections in report view

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#83]
Currently reports that have multiple sub-sections, e.g 'research companies' here https://infrastructure.sparcopen.org/landscape-analysis look a bit messy. 

@sssoz wondering if you'd have any ideas to address this that are very quick (~1-2 hours or so) to do from design to implementation (not including my time tagging various posts).

**Comment by ssssoz** [comment]
@JosephMcArthur I think grouping them into a sub-section makes iterating over each post a lot more complicated. We could simply add a small header for each of these, above the title. It might look a bit repetitive? 

<img width="1081" alt="Screenshot 2020-08-21 at 22 57 07" src="https://user-images.githubusercontent.com/6668406/90938683-a4d8e700-e401-11ea-9e3f-73399eb12726.png">

**Comment by ssssoz** [comment]
Will try something tomorrow.

**Comment by JosephMcArthur** [comment]
I think what you have there is better than what I've done at far :)

**Comment by ssssoz** [comment]
Just add `section: [section title]`  in the frontmatter for posts that belong to a section. See https://github.com/sparcopen/infrastructure/commit/43db3456a2ac123a846f4e2394882a59645be35b 

We could also add some logic so that the section title is only displayed once, at the top of a group of posts, but it might make the layout a lot messier (e.g. what would posts that don’t belong to any sections look like when displayed after a grouping?)

**Comment by ssssoz** [comment]
There’s one example here https://test.infrastructure.sparcopen.org/landscape-analysis

**Comment by JosephMcArthur** [comment]
That's great, I'll just update the front-matter accordingly to propagate :) Thanks!

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
updated! It looks a lot better, thanks
